tts_lang: "ru"
tts_timeout: 30
fps: 30
resolution: [1080, 1920]
categoryId: 24
privacyStatus: private
review_required: true
shorts_hashtags: ["#shorts", "#cats", "#funny"]
font: "DejaVuSans.ttf"
font_size: 64
brand_color: [20, 20, 25]
accent_color: [255, 255, 255]
caption_bg: [0, 0, 0, 140]
