services:
  - type: web
    name: shorts-bot-pro
    env: python
    runtime: python3
    pythonVersion: 3.11.0
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ADMIN_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: YT_CLIENT_ID
        sync: false
      - key: YT_CLIENT_SECRET
        sync: false
      - key: YT_REFRESH_TOKEN
        sync: false
      - key: DEFAULT_TAGS
        value: "shorts,viral"
      - key: TZ
        value: Asia/Almaty
