name: keepalive-and-daily-run

on:
  schedule:
    # каждые 10 минут — будим Render (время UTC)
    - cron: "*/10 * * * *"
    # ежедневные запуски пайплайна: 09:00 и 21:00 по Алматы (UTC+6) => 03:00 и 15:00 UTC
    - cron: "0 3,15 * * *"
  workflow_dispatch:

concurrency:
  group: youtube-keepalive
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render (health)
        run: curl -fsS https://youtube-zkp6.onrender.com/health || true

  daily:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Trends refresh (ignore errors if endpoint missing)
        run: curl -fsS -X POST https://youtube-zkp6.onrender.com/trends/refresh || true
      - name: Generate queue
        run: curl -fsS -X POST https://youtube-zkp6.onrender.com/trends/generate || true
      - name: Run queue (upload)
        run: curl -fsS -X POST https://youtube-zkp6.onrender.com/run/queue || true
