name: keepalive-and-3x-daily

on:
  schedule:
    # keepalive каждые 10 минут (UTC)
    - cron: "*/10 * * * *"
    # три запуска в день: 08:30, 14:30, 20:30 по Asia/Almaty (UTC+6) => 02:30, 08:30, 14:30 UTC
    - cron: "30 2,8,14 * * *"
  workflow_dispatch:

env:
  BASE: https://youtube-zkp6.onrender.com
  BATCH: "1"  # по одному шорту за запуск → 3/день

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render
        run: curl -fsS "$BASE/health" || true

  daily:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Refresh ideas
        run: curl -fsS -X POST "$BASE/ideas/refresh" || true
      - name: Generate N ideas into queue (no-op if generator expects separate step)
        run: |
          for i in $(seq 1 $BATCH); do
            curl -fsS -X POST "$BASE/trends/generate" || true
          done
      - name: Upload queue
        run: curl -fsS -X POST "$BASE/run/queue" || true
