name: Ops

on:
  workflow_dispatch:
    inputs:
      seed_month_start:
        description: "Дата старта для seed_month (YYYY-MM-DD)"
        required: false
      days:
        description: "Количество дней для seed_month"
        required: false
        default: '30'
      slot:
        description: "Слот времени, например '09:00 ET'"
        required: false
        default: '09:00 ET'
      run_queue:
        description: "Запустить очередь загрузки"
        type: boolean
        default: true
      fetch_trends:
        description: "Обновить тренды перед запуском"
        type: boolean
        default: true

jobs:
  execute:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_CLIENT_SECRET_JSON: ${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}
      YOUTUBE_TOKEN_JSON: ${{ secrets.YOUTUBE_TOKEN_JSON }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      CHANNEL_DEFAULT_TAGS: ${{ secrets.CHANNEL_DEFAULT_TAGS }}
      DEFAULT_CATEGORY_ID: ${{ secrets.DEFAULT_CATEGORY_ID }}
      DEFAULT_PRIVACY: ${{ secrets.DEFAULT_PRIVACY }}
      TZ_TARGET: ${{ secrets.TZ_TARGET }}
      TZ_LOCAL: ${{ secrets.TZ_LOCAL }}
      SERVICE_BASE_URL: ${{ secrets.SERVICE_BASE_URL }}
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      RENDER_DEPLOY: '0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch trending shorts
        if: inputs.fetch_trends == 'true'
        run: python -m tasks.fetch_trending_shorts
      - name: Seed month schedule
        if: inputs.seed_month_start != ''
        run: |
          python -m tasks.seed_month --start "${{ inputs.seed_month_start }}" --days "${{ inputs.days }}" --slot "${{ inputs.slot }}"
      - name: Run queue
        if: inputs.run_queue == 'true'
        run: python -m tasks.run_queue --upload
