name: Seed monthly topics now

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'Дата старта (YYYY-MM-DD, по ET). Оставьте пустым для значения по умолчанию.'
        required: false
        default: ''

jobs:
  seed:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL || vars.BASE_URL }}
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN || vars.ADMIN_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests python-dateutil
      - name: Seed monthly topics
        run: |
          python scripts/seed_month.py --start "${{ inputs.start || '' }}"
